### ISSUE TITLE
[improvement] bad inverted style for toggle buttons

### ISSUE THREAD

**Issue by DreadKnight** [CR6Community/CR-6-touchscreen#10]
Toggle buttons such as Fan and LED should have the circle on the right side when actually turned on, that's the standard way.

**Comment by Sebazzz** [comment]
Moved this to CR-6 touch screen repository.

---

I agree - feel free to submit a pull request with new bitmaps for the toggle buttons - or @Nushio are you able to take a shot at this?

**Comment by DreadKnight** [comment]
Yeah, had a feeling there's an even better repo for this. I've also found `Prepare/Disable stepper`. If any other inverted toggle buttons in the UI, feel free to list.

**Comment by Sebazzz** [comment]
They all use the same icon under the hood, so change one icon and you have them all.

**Comment by DreadKnight** [comment]
@Sebazzz Understood, good to know :+1:

**Comment by Sebazzz** [comment]
Already fixed by @grobux
