### ISSUE TITLE
Is it possible to add support for Marlin 2.1.x?

### ISSUE THREAD

**Issue by apassiou** [CR6Community/CR-6-touchscreen#101]
Marlin 2.1.x added Input shaping, the amazing feature people are spending hundreds of dollars on to get (Sonic Pad), or setting up Klipper. Marlin has it now. But there is no CR6SE touchscreen firmware that supports Marlin 2.1.x not from Creality (seems like it may never come since they would rather sell Sonic Pads), not from Community (community FW is frozen), not from anywhere else.

**Comment by ogni846** [comment]
would be very good

**Comment by Thinkersbluff** [comment]
Sadly, no.
The Marlin team did not reintegrate the CF firmware into the main stream.  The CF remains frozen at Marlin 2.0.8.1 and Marlin 2.1 does not support the CF interface.
