### ISSUE TITLE
Support for Ender 3 V2

### ISSUE THREAD

**Issue by dhysuiej** [CR6Community/CR-6-touchscreen#102]
I bought a touch screen advertised as an upgrade kit for Ender 3 V2. It turns out it's the same screen on the CR-6 but with a different bracket. Could your firmware work with this screen on the Ender 3V2?

![51h8+pS9VAL _AC_SL1384_](https://github.com/CR6Community/CR-6-touchscreen/assets/82825136/1dcd04b9-54a2-4559-97d8-c0aca1b79974)
![51f7YDmOgcL _AC_SL1000_](https://github.com/CR6Community/CR-6-touchscreen/assets/82825136/32b0cb3a-874f-4bb9-ad60-1ce62092e509)

**Comment by Thinkersbluff** [comment]
Only if you can compile the CF6.1 motherboard firmware (based on Marlin 2.0.8.1) for your printer and motherboard.

This Community firmware was specifically developed for the CR6 machines and the motherboard firmware is no longer being updated.  

There is one set of sample configuration files for an Ender 3 printer in the CF6.1 Source code that might help you: https://github.com/CR6Community/Marlin/blob/extui/config/ender-3-pro-v427-board-bltouch
