### ISSUE TITLE
When trying to install firmeware, the screen won't exit the.BIN file

### ISSUE THREAD

**Issue by tfmlink1** [CR6Community/CR-6-touchscreen#105]
When trying to install firmeware, the screen won't exit the.BIN file
I did the update but when I try to install the files on the touch it hangs on the .bin and doesn't run anymore.
Could someone help me?

**Comment by Thinkersbluff** [comment]
That is not an issue with the firmware itself.  That is typically an issue with the SD Card you are using.

Please review the help documentation here: https://cr6community-support-team.gitbook.io/cr6comm-touchscreen-refactored-firmware-docs/

if you are not able to solve your problem with that troubleshooting information, please join us on the Discord for more help.
