### ISSUE TITLE
FAN speed on printing screen

### ISSUE THREAD

**Issue by Ranney1** [CR6Community/CR-6-touchscreen#14]
Would be great to show the current fan speed on printing screen.
I'm using the aufo fan speed option when bridge is detected. Would be great to monitor this function!

**Comment by hughesjasonk** [comment]
> Would be great to show the current fan speed on printing screen.
> I'm using the aufo fan speed option when bridge is detected. Would be great to monitor this function!

I agree. that would be awesome

**Comment by Sebazzz** [comment]
@grobux did this already I think

**Comment by BubuMVX** [comment]
I added a lot of things. Unfortunately, I forgot about the fan speed... and now I'm again a little short on screen space.

![37_E_printing](https://user-images.githubusercontent.com/2005901/103283134-03c5f280-49d8-11eb-9259-321be77c9d13.png)

**Comment by Sebazzz** [comment]
I think this will not fall well with some people, but I think we can loose the Z-offset here. You can see it from the tuning screen anyway.

**Comment by BubuMVX** [comment]
It's OK for me. I implement this.

**Comment by Sebazzz** [comment]
If it really bothers some people we can move the printing speed (feed rate) to the header. Like "Printing     [100% speed]".

**Comment by BubuMVX** [comment]
Screen updated.

![37_E_printing](https://user-images.githubusercontent.com/2005901/103284367-5d7bec00-49db-11eb-8e27-8a81b72d473c.png)
