### ISSUE TITLE
[BUG] Displayed Disable Stepper ON/OFF "switch" state is affected by connecting Octoprint

### ISSUE THREAD

**Issue by Thinkersbluff** [CR6Community/CR-6-touchscreen#18]
When selecting the Prepare menu after powering-up the printer:
If Octoprint **is not** connected - The ON/OFF switch to the right of the "Disable Stepper" menu item shows **"OFF"** 
If Octoprint **is connected** - The ON/OFF switch to the right of the "Disable Stepper" menu item shows **"ON"** 

NOTE: I detected this while preparing to file a different bug report on the extui firmware, so please forgive what might be too much info in the attached log file.  
[Disable Stepper Bug Log.txt](https://github.com/CR6Community/CR-6-touchscreen/files/5604277/Disable.Stepper.Bug.Log.txt)

I suggest that the ON/OFF switch is not needed anyway, since this menu item only ever releases stepper motors it never activates them.  The menu item should just be called "Disable Steppers" and have no ON/OFF switch beside it, as it is on the Ender-3 LCD menu.

**Comment by Sebazzz** [comment]
@grobux is removing the toggle.

**Comment by Sebazzz** [comment]
Toggle has been removed
