### ISSUE TITLE
Filament change confusing

### ISSUE THREAD

**Issue by Nushio** [CR6Community/CR-6-touchscreen#2]
From the Facebook group, changing / loading filament isn't super clear.

Instructions (from Sonny Cantu)
1. Heat the hotend to 220C.
2. Open the lever on the extruder.
3. Push a little bit the filament through the extruder, then slowly pull the filament all the way out of the hotend, extruder, and filament sensor.

**Comment by Sebazzz** [comment]
Yes, it is not very guided. What do you suggest we do about it?

**Comment by Sebazzz** [comment]
Closed due to inactivity - but I think the latest designs by @grobux clear things up.
