### ISSUE TITLE
Getting this display when pressing the main PRINT button..

### ISSUE THREAD

**Issue by sinisterrainbow** [CR6Community/CR-6-touchscreen#20]
![IMG_20201219_071952115.jpg](https://user-images.githubusercontent.com/2353311/102692143-9c859280-41ce-11eb-8e7a-5a5a5b59e96b.jpg)

**Comment by Sebazzz** [comment]
Looks like you haven't flashed the correct firmware package. Please flash the official CF4 release package.

**Comment by Sebazzz** [comment]
Closed due to inactivity
