### ISSUE TITLE
EEPROM Default settings

### ISSUE THREAD

**Issue by chriskoups** [CR6Community/CR-6-touchscreen#24]
I am not sure if the default settings are saved in the screen (when you call M502) but the E jerk is not set. In default must be 5.0.

**Comment by Sebazzz** [comment]
Can you elaborate on that?

**Comment by chriskoups** [comment]
Morning, yes i can.
I flashed the complete RC5 with the screen and firmware on my CR-6 with MB 4.5.2. Then i press the "restore settings" on the screen so EPROM will be reset.
While i was printing, i notice some little bumps every ~10mm which were weird. I try to calibrate linear advance and when it was not 0 it was making a jittery noise.
I look the EPROM and the command M205 was outputting E0.00 which means the extruder is trying to achieve the speed with maximum acceleration and if they are high (i think are set to 5000?) Is cogging.
I fixed the problem by passing M205 E5.0, which is the same as the original EPROM.

**Comment by chriskoups** [comment]
Sorry, My bad! I am using EEPROM editor on octoprint and mess up the M205 command making the E0 despite set to 5! My bad....

**Comment by Sebazzz** [comment]
This is I think exactly the issue @Ranney1 ran into 😄

**Comment by Ranney1** [comment]
OMG, my stupid action is following me 😊🙈👌

**Comment by Sebazzz** [comment]
> 
> 
> OMG, my stupid action is following me 😊🙈👌

Wij zijn betrokken, maar niet onfeilbaar 😀
