### ISSUE TITLE
Printer does not store all settings properly

### ISSUE THREAD

**Issue by PatrickRobin83** [CR6Community/CR-6-touchscreen#29]
After Power up the Printer some settings wrong. 

Following Settings i set:

Sound --> off
Screen brightness --> 5%

After a rebooting the printer screen does not go into screensaver mode and the beeps for the touch feedback are on again although the Icon shows beeps off.

My english is not perfect. 
So if dont understand please ask. 

Everything else works perfect. 
Thanks in advance

**Comment by Sebazzz** [comment]
Thank you for your report. This has been resolved in this issue - https://github.com/CR6Community/Marlin/issues/113

Please check the issue for more details and workarounds.
