### ISSUE TITLE
Improve font rendering to prevent clipping and preserve proper kerning

### ISSUE THREAD

**Issue by coreyostrove** [CR6Community/CR-6-touchscreen#31]
I noticed some clipping of certain letters on the stock creality touchscreen LCD. See the attached photo for an example with the letter g.
![IMG_20210208_174747463](https://user-images.githubusercontent.com/78768318/107296970-0a647280-6a38-11eb-9164-b01bd3c47562.jpg)

**Comment by BubuMVX** [comment]
Hi @coreyostrove  and thanks for taking the time to report this issue.

We have this issue since the redesign of the firmware, but it hasn't been addressed since. Your message may be an opportunity to get back to it.

One solution could be to make lowercase letters small capitals. That way, all letters will stay in their available space. It will also harmonize with text in the pictures.

Some people are experimenting this idea on Discord, but DGUS isn't helping making nice fonts.

**Comment by Sebazzz** [comment]
@Thinkersbluff is also enjoying the wonders of DWIN font rendering 😅

**Comment by Thinkersbluff** [comment]
The DGUS font clipping behaviour takes many forms with a variety of contributing factors.  The photo in this issue description seems directed at the clipping of descenders.  I have been exploring ways to improve on that. Aesthetics are a large part of resolving this issue. The current implementation may yet turn out to be the best balance, but I have not given up trying.
This is a different font but these two photos demo one option.  Using FontForge, the 5 glyphs with descenders can be edited to bring the descenders up to the baseline, for instance.  Another option is to use small caps.
![1B5DC298-410A-46E8-BE8A-0736038977EB](https://user-images.githubusercontent.com/36551518/107530627-12342c00-6b8a-11eb-9284-1a635d226868.jpeg)
![4F0E7E45-5090-42FC-8DE4-4AD65CC44D92](https://user-images.githubusercontent.com/36551518/107530813-355edb80-6b8a-11eb-83d4-0d0be589b3d4.jpeg)

Notice that if I try to take advantage of increasing the font size to take advantage of the descenders being raised, then numbers don’t fit fields as well.  The modified font may also not be as pleasing to the eye.  

I am hoping small caps is a better answer, but it still has its issues. 

![108312DE-C50C-420A-8111-1D3A1A532EE2](https://user-images.githubusercontent.com/36551518/107532544-021d4c00-6b8c-11eb-9189-f1b2eab2c41b.jpeg)

 Just scaling the caps down gives serious anti-aliasing problems with the current font. Other fonts like SegoeU are getting clipped on left or right side of some characters on some screens and character spacing/kerning is not working.  
 
The tools are not well documented, so it will take time and patience to finesse this issue. I will share any reasonable looking fonts I can.

**Comment by Thinkersbluff** [comment]
![F20D5473-BD27-4CCA-9DFF-00B3EEE44A19](https://user-images.githubusercontent.com/36551518/107562157-74525880-6bad-11eb-8db9-244a3fd472bd.jpeg)

I find this font to be a reasonable alternative to the B612Mono font being used now.  The sides of some letters still get clipped in some display fields, for reasons I have not yet understood, so it is not “perfect” but I can do no better for now.

[0_DWIN_ASC.HZK.ArialMonoMtPro.zip](https://github.com/CR6Community/CR-6-touchscreen/files/5961057/0_DWIN_ASC.HZK.ArialMonoMtPro.zip)

There are two versions of the font file in the attached .zip.
To use either of these files:
 - "Extract All" somewhere.  
 - Rename whichever font file you want to use to 0_DWIN_ASC.HZK and copy/paste it into the DWIN_SET folder on the SD card you will use to reflash your display.
The file 0_DWIN_ASC.HZK.ArialMonoMTPro_SmCaps-CR6 is the small caps version you see in the attached photo.
The file 0_DWIN_ASC.HZK.ArialMonoMtPro_Reg-CR6 is the same Arial Mono MT Pro file as the Small Caps one, but with the regular lower-case character glyphs.  The descenders still get clipped on the Regular font, but some users may prefer the aesthetics of lower case characters over the aesthetics of small caps.

NOTE: The original font file for these was downloaded from https://www.cufonfonts.com/font/arial-mono-mt-pro on 10 Feb 2021, modified in FontForge, converted using DGUS Tool 8.0.1.1 and uploaded here.  It is licensed as "free for personal use only"

**Comment by Sebazzz** [comment]
I suspect it has something to do with the height of the fields, but I can't be sure. There is this weird vertical height and horizontal weight parameter in the DWIN editor.

**Comment by Thinkersbluff** [comment]
Limiting factor for “happy” fonts seems to be screen dpi and font size.  Top picture shows 70% scale for small caps. Lower shows 90% scale. All other factors the same in DGUS.

![F0E587F4-B3A5-407C-A697-09BBE7EB7C28](https://user-images.githubusercontent.com/36551518/107582481-8ccf6c80-6bc7-11eb-9472-d274efa3f355.jpeg)
![A6CEF64C-990E-4481-BE6A-EC5DBBD5B7EF](https://user-images.githubusercontent.com/36551518/107582482-8e009980-6bc7-11eb-8754-57426879a8de.jpeg)

**Comment by Thinkersbluff** [comment]
FWIW - It is simple to substitute the HZK (font) file distributed with the Creality DWIN_SET for the one bundled with the Community Firmware. Just copy 0_DWIN_ASC.HZK from the Creality DWIN_SET folder, paste it into the Community Firmware DWIN_SET folder, and reflash the Touchscreen.  That font has shorter descenders, which are not truncated by DGUS. The tradeoff will be that the Community Firware font was edited to replace the backward apostrophe character with the degrees symbol, so all fields with units of degC will now show that character instead of the degrees symbol.

![image](https://user-images.githubusercontent.com/36551518/171012944-86637ef6-0fdf-4f58-aa81-b2dca25982be.jpeg)

**Comment by Thinkersbluff** [comment]
The Re-Factored Version1.1 released 13 March 2023 implements a new HZK file which solves the problem with descenders, though it also shrinks the message font slightly in the process.
