### ISSUE TITLE
Text of note on Change FIlament screen is out of date

### ISSUE THREAD

**Issue by Thinkersbluff** [CR6Community/CR-6-touchscreen#36]
The Change Filament control button labels recently changed to Load/Unload, but the text of the instructions on that screen still says "extrude/retract".  It would be helpful to change the note to also say "Load/Unload".

**Comment by Sebazzz** [comment]
Agree. Leaving this to @grobux because I don't know anything about GIMP and PSDs.

**Comment by Thinkersbluff** [comment]
Corrected this in new RC refactored version.
