### ISSUE TITLE
ICL tool in english

### ISSUE THREAD

**Issue by nicwilson58** [CR6Community/CR-6-touchscreen#53]
Apologies if this is in the wrong place, it is not obvious where to put such a question.

I have the V8.0 tools from the supplied link and it's fine.  However, I am unable to find the English version of the ICL tool as shown in the example.   I have found the "AllTool.exe" which is the Chinese version and it does work OK so really not an issue,  it might be able to set it to English but it's not clear either.  Is there an English copy or a way to set the language of the Chinese version?

**Comment by nicwilson58** [comment]
found it

**Comment by Sebazzz** [comment]
From the DWIN tool itself, as you've found out 👍 
I'm not sure how and if it is possible to run the tool standalone with the correct language.
