### ISSUE TITLE
Filament Change (M600) number of beeps. 

### ISSUE THREAD

**Issue by ghost** [CR6Community/CR-6-touchscreen#62]
Can the number of beeps on M600 be reduced to say 2 or 3?

**Comment by Ranney1** [comment]
If I am correct, you can change this by yourself. In marlin, in the config_adv file, search for the M600 command. Here you can change the behavior of the M600 command. Then recompile.

**Comment by Sebazzz** [comment]
This is indeed hardcoded and can be changed in Configuration_adv.h in the ADVANCED_PAUSE_FEATURE section.
