### ISSUE TITLE
Touchscreen reads, "build 61166 found but expected 61" after flashing the CF6.1 firmware

### ISSUE THREAD

**Issue by joshgebbie** [CR6Community/CR-6-touchscreen#65]
I turned off my machine after the last print and when I turned it on again it had an error "Please flash your TFT screen: version mismatch - build 61166 found but expected 61" I reset factory settings and re flashed the display and got the same error.

**Comment by Sebazzz** [comment]
Try flashing an older touch screen firmware and then reflash this firmware again. It appears spontaneous corruption.

You may also try to flash the clean format files posted by @grobux in another issue to clear all flash memory.

Met vriendelijke groet,
Sebastiaan Dammann
________________________________
Van: Josh ***@***.***>
Verzonden: Tuesday, October 12, 2021 7:56:32 PM
Aan: CR6Community/CR-6-touchscreen ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [CR6Community/CR-6-touchscreen] please flash tft screen (#65)


I turned off my machine after the last print and when I turned it on again it had an error "Please flash your TFT screen: version mismatch - build 61166 found but expected 61" I reset factory settings and re flashed the display and got the same error.

**Comment by joshgebbie** [comment]
I tried using the last firmware and the error message changed to "Please flash your TFT screen: version mismatch - build 60 found but expected 61" so there was a change then when I reinstalled the newest firmware I got the same message "Please flash your TFT screen: version mismatch - build 61166 found but expected 61". I cant find a post explaining how to clean format to clear flash memory I barely know what I'm doing now.

**Comment by joshgebbie** [comment]
Update: I found the clearing instructions, cleared it and tested and while the screen was blank it made the same beeping noise as before when had the error. When i put on the newest firmware again the error code was still there. Is it possible it has something to do with the machine firmware?

**Comment by joshgebbie** [comment]
downgraded motherboard got error saying "Please flash your TFT screen: version mismatch - build 61166 found but expected 60" then when I upgraded motherboard to newest firmware got the same "Please flash your TFT screen: version mismatch - build 61166 found but expected 61" issue.

**Comment by Sebazzz** [comment]
Very curious. I don't have a direct response except that you can recompile the firmware yourself to get rid of the message.

**Comment by joshgebbie** [comment]
I was able to plug in my octoprint while it was starting and while it popped up with the message i sent a print to it and it seems to be working fine. Still has the error message but at least it didn’t brick my machine. 

I wouldn’t even begin to know how to recompile the firmware myself. I had to use Visual Basic for my Ender 3 back in the day but I was following YouTube for that.

**Comment by mustafakalash** [comment]
I am having the same issue on 1 out of 4 of my CR-6 SEs after updating to 6.1. It is definitely the screen. I swapped screens with one of the printers that was working after the update and the error followed the screen. I tried all of the suggestions here with the same results. The printer does appear to work normally, despite the error.

**Comment by Sebazzz** [comment]
Yes, the check is only a "soft" check to help people because on stock CR-6 either the touch screen or the motherboard doesn't always flash correctly and need several attempts.

**Comment by Sebazzz** [comment]
Since this is a hardware issue, I'Il close this.

**Comment by StephenBrough** [comment]
Have the same issue, tried flashing the screen about 10 times. Also tried flashing older community firmware and then 6.1, also tried flashing official firmware and then 6.1. Will try compiling out that check next.
