### ISSUE TITLE
M73(Print progress) amd M117 (Message) support for Octoprint

### ISSUE THREAD

**Issue by Ranney1** [CR6Community/CR-6-touchscreen#7]
Would be great if we can find a way to make the LCD switch to the 'print' screen while printing with Octoprint.
Most important functions would be M73 support (print progress) and M117 (display message)
If possible, Filament runout support for Octoprint would be great.

**Comment by Sebazzz** [comment]
I'm currently re-engineering the UI on top of ExtUI. That should pretty much automatically cause this to work as expected.

**Comment by Sebazzz** [comment]
Reading again, it are three things you're asking:

1. Go to the "print screen" when printing through a host
2. Support M73 (print progress)
3. Support M117 (custom messages)

**Comment by Ranney1** [comment]
Dear Sebazzz,

Thank you! That is exactly where I was looking for! Thank you again for the really good firmware and all your time!

**Comment by Ranney1** [comment]
Please note that the LCD is not closing the ABL screen when it is finished with leveling. So I think that the 'print screen' must be triggered after ABL.

**Comment by Ranney1** [comment]
Maybe that this code is also nice to implement?
M355 - Case Light Control
To turn on/off the led on the hotend by gcode/remote?

**Comment by Ranney1** [comment]
Update: LED control is actually possible by GCODE. 
M42 P6 S0 ; is led off
M42 P6 S255 ; is led on

**Comment by Sebazzz** [comment]
M355 implemented on extui, as well as M117.

**Comment by Ranney1** [comment]
Ahh, really great! Looking forward to the moment that it is also working when printing with octoprint!
Thanks again for your great work!

**Comment by Sebazzz** [comment]
M73 is now implemented in extui branch

**Comment by Sebazzz** [comment]
Ready for next release.
