### ISSUE TITLE
DW7.7.5 on Creality Sermoon D1

### ISSUE THREAD

**Issue by tommy536** [CR6Community/CR-6-touchscreen#72]
I found a couple of bugs in the newest release.

- Printer build platform isnt correct > X280; Y260; Z310
- The control of the Z-Axis is inverted
- No Standard Marlin connection via micro usb? The Creality 3D Pad wont work > always connecting (all baud rates)
- All Display Pictures have a bad resolution (V7)

The rest seems to be fine. Thanks a lot for ur hard work!

**Comment by Thinkersbluff** [comment]
What is DW7.7.5?

Which "latest" release?

This is only the touchscreen firmware to work with the CR6Community Firmware 6.1-Final. 
It is not intended to work on Sermoon.
