### ISSUE TITLE
Stuck in boot loading

### ISSUE THREAD

**Issue by jayse2006** [CR6Community/CR-6-touchscreen#76]
Printer says the bootloader is confused. attempted to reflash the firmware but it wont do anything other than display the start screen.

**Comment by Thinkersbluff** [comment]
This is not enough information for me to help you.
That error message says try another card.  If that is not helping, you may do better raising this as a discussion in the Discord channel.

**Comment by jayse2006** [comment]
I’ve tried a different card and even tried booting without the SD card in it. It’s been left on over night to give it time to try and boot. It has worked for months with the firmware and now this pops up

**Comment by jayse2006** [comment]
![Uploading image.jpg…]()

**Comment by Thinkersbluff** [comment]
> It has worked for months with the firmware and now this pops up

If the printer worked on this firmware for months, then it does not sound like this is a bug in the firmware.  It sounds more like the firmware is working correctly, but the motherboard bootloader is not.  

I recommend that you come discuss your hardware issue on the Community.

 https://discord.gg/yDY6pb2BQS
