### ISSUE TITLE
Strange screen is displayed on Touch Screen firmware flashing.

### ISSUE THREAD

**Issue by junonara** [CR6Community/CR-6-touchscreen#78]
I just ordered an additional touch screen for the CR-6 SE and it was delivered.

While flashing the new CR-6 SE's touch screen using the 61F_RC_290422_v1 released by CR6Community/CR-6-touchscreen, near completion, a white noise-like screen appears.
![Flashing3](https://user-images.githubusercontent.com/96027590/167519966-102e1db4-7a0e-4ded-b7ad-90b4544b3786.jpg)

It looks like the flashing is almost done right before the white noise display.
![Flashing1](https://user-images.githubusercontent.com/96027590/167519988-3b1d0622-ff83-48cf-82b3-bf2dc231bf62.JPG) ![Flashing2](https://user-images.githubusercontent.com/96027590/167519995-3125169b-2880-4b3f-8e69-072a9afd001d.JPG)

The new touch screen uses the same PCB as the old LCD. However, flashing completion is indicated differently. However, if I wait a few tens of seconds and turn on the CR-6 SE, it operates normally (displaying icons, selecting menus, etc.).

First, to check the kernel version, I checked the kernel version by flashing using an empty DWIN_SET, and at this time, the normal completion screen was displayed. After flashing using the contents of DWIN_SET, a strange completion screen is displayed.
![Flashing End](https://user-images.githubusercontent.com/96027590/167520048-bb61e388-3d2b-42a4-8ea0-3b7c47d87ef6.jpg)

On the touch screen I had it shows the normal completion screen. It is strange because it is a symptom that appears on a new touch screen that uses the same PCB.

**Comment by scratchfury** [comment]
The white noise screen occurs when the screen has to change orientation.  If you power it off and back on, it should display normally in the new orientation.  If it was a new screen, it was probably in orientation 0 and the CR-6 uses 270.

**Comment by Sebazzz** [comment]
Interesting. I've never seen noise!

Met vriendelijke groet,
Sebastiaan Dammann
________________________________
Van: scratchfury ***@***.***>
Verzonden: Tuesday, May 10, 2022 3:34:05 AM
Aan: CR6Community/CR-6-touchscreen ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: Re: [CR6Community/CR-6-touchscreen] Strange screen is displayed on Touch Screen firmware flashing. (Issue #78)


The white noise screen occurs when the screen has to change orientation. If you power it off and back on, it should display normally in the new orientation. If it was a new screen, it was probably in orientation 0 and the CR-6 uses 270.

**Comment by Thinkersbluff** [comment]
I know the 4.5 calibration process is performed in landscape orientation. I wonder if they left it in that orientation at the factory. 
I would have expected that empty DWIN_SET flash to have been in landscape in that event. 
Glad it is ok now. 
I will double-check the T5L CFG file to be sure I did not accidentally include any calibration switches in that. 

UPDATE 10May2022 - Happily, I can now confirm that the file T5LCFG_272480.CFG I bundled with the refactored DWIN_SET is the same file distributed with the CF6.1-Final Touchscreen firmware. No accidental switches set in that file.

**Comment by junonara** [comment]
If the calibration or rotation setting is wrong, the same phenomenon should appear on two touch screens of the same PCB version, but this phenomenon appears on the touch screen purchased later. Of course, I think that even the same PCB may contain HW with different factory settings or slightly different physical signal timing.

Once the white noise screen is displayed, it is not possible to know exactly when the flashing is completed, but if I turn it off and on after about 30 seconds, new touch screen works normally, so it is in use for now.

**Comment by Thinkersbluff** [comment]
Actually it is not the hardware, it is the operating system, that makes two of these screens behave differently.  
Each display is calibrated at the factory.  
At DGUS2 v4.5, the calibration itself changed, which is why we have refactored the CF DWIN_SET. 
Which OS is on your first screen?

**Comment by junonara** [comment]
The kernel version shown at the first flashing using empty DWIN_SET was T5L1 DGUS2 V4.5 2022.01.13, and when flashing by copying the contents of the DWIN_SET folder, a white noise screen appeared and flashing again with T5L_UI_DGUS2_V45_20220105.BIN. The version I see when booting the CR-6 SE is 6.1F_RC_290422_v1.

**Comment by Thinkersbluff** [comment]
I missed that detail, in the photo with the white noise.

Why did you add a DGUS BIN file to the DWIN_SET folder when flashing the refactored DWIN_SET?

I am surprised and disappointed to see that although the display says it was already flashed with DGUS2 v4.5, the date stamp on it is not the same date stamp as the bin file you flashed, so we can not be sure whether it was the same OS, either.

**Comment by junonara** [comment]
After flashing DWIN_SET (without kernel), a noise screen appeared and I thought it was a kernel problem, so I flashed with the kernel again.

Empty DWIN_SET -> check kernel version : T5L1 DGUS2 V4.5 2022.01.13 -> DWIN_SET(without kernel) -> noise screen -> DWIN_SET(with kernel : T5L_UI_DGUS2_V45_20220105) -> noise screen

**Comment by Thinkersbluff** [comment]
Sorry. I have no other knowledge to share, here.  I am baffled.

if you remove the CFG file from the DWIN_SET folder and flash again, the noise screen may not appear.  It is the CFG file that commands the screen hardware to change orientation or mode.

**Comment by Sebazzz** [comment]
Yes and the orientation is actually overridden via a command after the firmware initializes.

Met vriendelijke groet,
Sebastiaan Dammann
________________________________
Van: Thinkersbluff ***@***.***>
Verzonden: Wednesday, May 11, 2022 6:43:32 AM
Aan: CR6Community/CR-6-touchscreen ***@***.***>
CC: Sebastiaan Dammann ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [CR6Community/CR-6-touchscreen] Strange screen is displayed on Touch Screen firmware flashing. (Issue #78)


Sorry. I have no other knowledge to share, here. I am baffled.

if you remove the CFG file from the DWIN_SET folder and flash again, the noise screen may not appear. It is the CFG file that commands the screen hardware to change orientation or mode.

**Comment by junonara** [comment]
After deleting T5LCFG_272480.CFG from the DWIN_SET folder and flashing, the completion screen is displayed normally. Thanks!!
![IMG_20220511_161217_DRO](https://user-images.githubusercontent.com/96027590/167791725-978bc4e2-570e-40c5-b0f8-49a297d753e8.jpg)

**Comment by Sebazzz** [comment]
It might have something to do with other parameters in the CFG file. For instance: capacitive vs resistive touch screen is also configured there I think.

Met vriendelijke groet,
Sebastiaan Dammann
________________________________
Van: junonara ***@***.***>
Verzonden: Wednesday, May 11, 2022 9:20:14 AM
Aan: CR6Community/CR-6-touchscreen ***@***.***>
CC: Sebastiaan Dammann ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [CR6Community/CR-6-touchscreen] Strange screen is displayed on Touch Screen firmware flashing. (Issue #78)


After deleting T5LCFG_272480.CFG from the DWIN_SET folder and flashing, the completion screen is displayed normally. Thanks!!
[IMG_20220511_161217_DRO]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F96027590%2F167791725-978bc4e2-570e-40c5-b0f8-49a297d753e8.jpg&data=05%7C01%7C%7C3b2453394ad64967313808da331eb1d2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637878504162374192%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lbSqq4GM%2FHZzmFXDH5c4FKG6jsG5kwzRQumeZ0N8Vkw%3D&reserved=0>

**Comment by Thinkersbluff** [comment]
> After deleting T5LCFG_272480.CFG from the DWIN_SET folder and flashing, the completion screen is displayed normally. Thanks!!

Glad to hear it.
I will leave this issue open for a while, so that others can find it more easily.  

@Sebazzz - There is so much online info now about flashing CF6 and of course  no mention of this DGUS2 calibration issue in the June 2021 release files.  I expect we will be hearing more and more from folks receiving new printers and replacement displays who have not yet heard about the refactoring of DWIN_SET or of the calibration issues with DGUS2 at 4.5+

Are you thinking of using the Announcement or Releases channel, to “promote” this change from RC to full release?

Will you need other user feedback on this RC before you decide next steps?

**Comment by Sebazzz** [comment]
It is not a matter of deciding, because I think it is ready to go. With a note that this primarily meant to resolve issues for users with newer hardware, and not an upgrade for existing printers. The only question remains whether we have documented enough.

**Comment by Thinkersbluff** [comment]
Cursed with an Engineer's brain. I still have questions. 
Will you pull this release into the main board zip files (e.g. as a maintenance release, like 6.1.1), or leave folks to discover the refactored Touchscreen firmware here?

**Comment by Thinkersbluff** [comment]
UPDATE: It may be coincidental, but this issue has not been reported again, since we stopped using the build script to assemble DWIN_SET for the release. That script renamed ICL files 13 and 14.  Maybe that name change "bothered" this new version somehow.

**Comment by Thinkersbluff** [comment]
Since there have been no more reports or observations of this problem since we stopped renaming files 13 and 14, that is now the recommended standard practice. This issue is closed.
