### ISSUE TITLE
Wrong message displayed when print canceled

### ISSUE THREAD

**Issue by ritchiedc** [CR6Community/CR-6-touchscreen#8]
When a print is canceled the correct code is sent to the screen but the file "61_E_Autohome" actually displays a message saying "Automatic Bed Leveling Please Wait".

**Comment by Sebazzz** [comment]
@Nushio Can you fix the bitmap in the extui branch. It should say "homing" (like the stock firmware)

**Comment by Sebazzz** [comment]
FYI @grobux

**Comment by Sebazzz** [comment]
Fixed by @grobux
