### ISSUE TITLE
How do I use the LEVELING SETTING menu in the Calibrate menu?

### ISSUE THREAD

**Issue by junonara** [CR6Community/CR-6-touchscreen#83]
I know that the CR6Community's firmware has a "Fade height" setting function in the "LEVELING SETTINGS" menu. But when I click the "LEVELING SETTINGS" menu in the "Calibrate -> BED LEVELING" menu, nothing happens. If I click LEVELING SETTINGS, the sub menu should be displayed, but the sub menu is not displayed and stays in the LEVELING menu.

The picture of the Fade Height setting in the Community Firmware release 6.1's release notes is as follows.
![24f19e1368ca](https://user-images.githubusercontent.com/96027590/170396003-e6433cb8-0256-4c79-85d7-a9d68af9739f.jpg)

I don't know if this is a 3d printer firmware issue or a touch screen firmware issue. Is there another way to enter the LEVELIN SETTINGS menu?

**Comment by Thinkersbluff** [comment]
Might be specific to your system.

No problem getting here on my system:

![image](https://user-images.githubusercontent.com/36551518/170409108-a3ea545f-ce50-4c40-aac8-66485889690e.jpg)

Which touchscreen firmware do you have loaded?

**Comment by junonara** [comment]
I used 61F_RC_090522_v2. And 61F_RC_290422_v1 is the same. The 3D printer firmware is Community 6.1 version, and only Configuration.h has been modified using the configs of cr6-se-v4.5.3-mb.

#define FIL_RUNOUT_ENABLED_DEFAULT false
#define DEFAULT_LEVELING_FADE_HEIGHT 10.0

Sorry, my touch screen seems to have a lot of issues. The FADE HEIGHT setting has been modified in the community firmware and is being used, so even if it cannot be used in the UI, there is no problem right now.

**Comment by Thinkersbluff** [comment]
> I used 61F_RC_090522_v2. And 61F_RC_290422_v1 is the same

Ah, sorry, I should have asked that question first.
You may have found an error in the refactoring. It is 3 am as I write this reply and I have a 2 hr print job running.  I will check tomorrow and get back to you.

**Comment by Thinkersbluff** [comment]
So, I definitely see issues on the page itself, which I will address with a new RC, but I had no trouble getting here with v2.  Have not yet tried v1.

I do not know of any other way to get to that page, but per the UI philosophy, I think it could make sense to add a button to the Setup menu…. I will explore that idea, too.

![B5D26D7E-69A4-4D99-B041-2BE8A57A10B5](https://user-images.githubusercontent.com/36551518/170525215-5ed260fe-885b-461d-b823-81066ccef846.jpeg)

**Comment by Thinkersbluff** [comment]
Please try flashing this repaired RC and let me know if it works?
[DWIN_SET.zip](https://github.com/CR6Community/CR-6-touchscreen/files/8781281/DWIN_SET.zip)

**Comment by junonara** [comment]
I flashed the DWIN_SET you sent to the touch screen and modified the community firmware source to confirm that the screen output is normal. The community firmware source modification is Marlin\src\lcd\extui\dgus_creality\creality_touch\DGUSDisplayDef.cpp.

![DGUSDisplayDef](https://user-images.githubusercontent.com/96027590/170602916-71755767-a08e-4986-9aff-722cef4c167d.jpg)

The UI processing part of LEVELING SETTINGS was blocked by an unused definition called HAS_BED_PROBE_SETTINGS. After changing the HAS_BED_PROBE_SETTINGS to HAS_PROBE_SETTINGS and updating the 3D printer, it was possible to enter the LEVELING SETTINGS menu and the menu icons are displayed normally.

![IMG_20220527_084641_DRO](https://user-images.githubusercontent.com/96027590/170603314-29ec757b-d398-4bb3-9899-b6846bbd0d85.jpg)

Thanks for your help every time.

**Comment by Thinkersbluff** [comment]
> The UI processing part of LEVELING SETTINGS was blocked by an unused definition called HAS_BED_PROBE_SETTINGS. After changing the HAS_BED_PROBE_SETTINGS to HAS_PROBE_SETTINGS and updating the 3D printer, it was possible to enter the LEVELING SETTINGS menu and the menu icons are displayed normally.

I am very happy for you that your edits solved your problem.
I am equally mystified as to why you found that necessary, as my own system still has the original "HAS_BED_PROBE..." line in Marlin\src\lcd\extui\dgus_creality\creality_touch\DGUSDisplayDef.cpp, and it is working fine.

No one should have to edit the CF6.1-Final mainboard firmware, to use the refactored DWIN firmware.
