### ISSUE TITLE
[QUESTION] There's compatibility with Ender5 Pro? 4.2.2 board STM32F103RE_creality chip

### ISSUE THREAD

**Issue by zonalimitatore** [CR6Community/CR-6-touchscreen#88]
Hello.
Like title. There is a solution to make this screen work on an Ender 5 Pro? My client say "only Creality's logo show" and no more.
Obviously, i've defined DWIN_CREALITY_TOUCHLCD

Another client with Ender V2 4.2.7 board, work successfully!
Thanks

**Comment by Thinkersbluff** [comment]
Sorry, no. Not here.
Have you tried the InsanityAutomation version or Marlin 2.1?

**Comment by zonalimitatore** [comment]
> Sorry, no. Not here. Have you tried the InsanityAutomation version or Marlin 2.1?

Hum, no. I build it from 0. Tha instanity, works?

**Comment by Thinkersbluff** [comment]
Best to ask them here:
https://discord.gg/nsN7xRaTwp

**Comment by zonalimitatore** [comment]
Thanks
