### ISSUE TITLE
(FR) Display axis positioning on print screen

### ISSUE THREAD

**Issue by hondrus31** [CR6Community/CR-6-touchscreen#9]
### Description

Not sure if this request should be posted here, on marlin git, or both.
I think that percentage bar showed on screen makes difficult to understand the progression of your print.
While X/Y value is more a gimmick, Z value can be useful. For example: you set a "pause at height" to insert a magnet in your print, reading the exact height of the Z axis will let you know how many layers you have to wait.

I made up an example of how the print screen would look like:
![37_E_printing](https://user-images.githubusercontent.com/58083279/97223948-c030eb80-17d0-11eb-8ab6-51301e080fff.png)
[37_E_printing.zip](https://github.com/CR6Community/CR-6-touchscreen/files/5441307/37_E_printing.zip) - this zip file contains a bmp image, github wouldn't let me post it here as is.

**Comment by Sebazzz** [comment]
Actually, I don't even think showing the Z offset all the time is very useful is it? I think the axis might even be shown under the speed/z-offset part perhaps.

**Comment by hondrus31** [comment]
Yeah, Z offset is pretty useless, constantly showed like right now.
And I imagine that swapping Z offset value with Z axis value would be easier to code, right?

**Comment by Sebazzz** [comment]
We won't show X/Y axis positioning because the overhead and delay of updating it on screen is quite high. However, the Z-axis position is useful, so @grobux is incorporating that in the redesign.

**Comment by Sebazzz** [comment]
There is some space below the Z-offset for the Z-axis position, and at the left side below the "speed dial" there is space for the extrusion rate (flow rate).

**Comment by BubuMVX** [comment]
Feature added in `extui-dev`, thanks @hondrus31 for the suggestion.

![Preview](https://user-images.githubusercontent.com/2005901/103250886-79997200-4976-11eb-8d44-d6d80c637924.png)
