### ISSUE TITLE
Can this be used with the Creality v4.2.7 board?

### ISSUE THREAD

**Issue by jmartens2** [CR6Community/CR-6-touchscreen#93]

**Comment by jmartens2** [comment]
Sorry as the title asks, can it be used with the Creality v4.2.7 board?

**Comment by Thinkersbluff** [comment]
This firmware only works on the T5L 272x480 DWIN display, and only when paired with the mainboard Community Firmware v6.1-Final.

You may, however, find that InsanityAutomation has a similar product which is compatible with your board.

https://discord.gg/VZuGRtrvuq

**Comment by Sebazzz** [comment]
Technically you can compile it for your board of course.

Met vriendelijke groet,
Sebastiaan Dammann
________________________________
Van: jerry martens ***@***.***>
Verzonden: Saturday, November 12, 2022 3:39:50 AM
Aan: CR6Community/CR-6-touchscreen ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: Re: [CR6Community/CR-6-touchscreen] Can this be used with the Creality v5.2.7 board? (Issue #93)


Sorry as the title asks, can it be used with the Creality v4.2.7 board?
