### ISSUE TITLE
Are this JPEG artifacts on the screen?

### ISSUE THREAD

**Issue by zappanaut** [CR6Community/CR-6-touchscreen#94]
Hi there!

Thanks a lot for keeping the CR6 alive!

When reviving mine today after months of collecting dust I first flashed some new firmware. I noticed that the screen looked a bit blurry and thought that these were just my fingerprints, but it turned out it looks very much like jpeg artifacts.

Is this due to a glitch during the build process or something unavoidable?

![blurry](https://user-images.githubusercontent.com/33423139/207965138-f8194c8b-748d-4112-9f49-59cd67a66a74.jpg)

**Comment by Thinkersbluff** [comment]
Yep, probably jpeg artifacts.

**Comment by Thinkersbluff** [comment]
[The Refactored version 1.1 released 13 March 2023](https://github.com/CR6Community/CR-6-touchscreen/releases/tag/Re-Factored_v1.1) has been built from scratch, using the original CF6.1 screen bitmaps and minimizing jpg compression.  The colour scheme has also been restored to black/grey/red.

Hopefully, this solves the compression artifacts problem flagged here.
![IMG_20230313_140715](https://user-images.githubusercontent.com/36551518/224790761-a044d281-4044-4567-975a-7e8c81c836da.JPG)
