### ISSUE TITLE
CR6 MAX w/ Community Firmware v6.1, and Failed Prints from Heater Timeout after Filament Runout

### ISSUE THREAD

**Issue by moadster** [CR6Community/CR-6-touchscreen#95]
Ever since I installed Community FW around 1.5 years ago, if the machine runs out of filament and is stopped by the runout sensor, then sits idle for 30 minutes or more, the hot-end heating element will timeout, and there will be an indication of such on the display. After this happens, no matter what you try, you cannot get the hotend to reheat. (I've tried hitting "Resume", manually setting the temperature, and going through the filament swap procedure)

It will display that you've selected a temperature, but it won't try to send power to the heating element, and there will be no change in temperature. After around 30 seconds, you'll get the yellow box "Heating Failed" message, which can only be remedied by a machine reboot, and this typically ruins the print because it skips the layer it was currently on when it tries to recover the print.

I've been running v6.1 Community FW, and DGUS v3.5 for the entirety of machine ownership. I have updated the touchscreen a couple times with the latest firmware, but the issue has persisted through multiple updates to the touchscreen. There hasn't been an update to the Community FW since I installed v6.1. I have tried with and without PID tuning prior to the print. The machine is completely stock, and I've never had a heating failed error in any other scenario (all of the hardware and wiring is good)

Would love some help with this! It stinks having to watch the machine like a hawk for when the filament runs out (which happens all of the time with 400mm^3 volume)

Thanks!
![20230111_205614 (1)](https://user-images.githubusercontent.com/53929636/212171031-119cf9a1-b986-4d71-9f57-f2f1728abcae.jpg)

**Comment by Thinkersbluff** [comment]
This is not a display firmware issue, it is a design feature of the mainboard firmware.
