### ISSUE TITLE
[info] Compatible with CR10 Smart Pro?

### ISSUE THREAD

**Issue by boromyr** [CR6Community/CR-6-touchscreen#96]
I wanted to know if this firmware would be compatible with CR10 Smart Pro, obviously with the screen in portrait mode. Thank you.

Any response or opinion releases you from any liability for any damage or malfunction.

**Comment by Sebazzz** [comment]
It should be doable, but there is much uncertainty in regard to the board (as Creality has released limited documentation), and the touch screen (as Creality tends to switch manufacturers or the manufacturer tends to have weird compatibility in terms of firmware). Given that these two aren't too much different, it shouldn't be too hard to get it working.

**Comment by boromyr** [comment]
I read up on the type of screen, and on the CR10 Smart it has already been documented loading your firmware, and it seems to work, the screen on the CR10 Smart Pro is almost identical, except for the serial number, some capacitors, and some other electronic details. I suspect it's some limited run or a different vendor, but it's still a DGUS2 T5L. A user told me that he used the CR10 Smart screen in a CR10 Smart Pro and also updated the firmware, so I think he can run your CR6 firmware.

**Comment by Thinkersbluff** [comment]
This issue seems to be answered.
