### ISSUE TITLE
Stuck on UI loading screen

### ISSUE THREAD

**Issue by wheetboi** [CR6Community/CR-6-touchscreen#98]
![IMG_20230330_125132](https://user-images.githubusercontent.com/77525741/228936213-0e036b7c-4f9d-408b-8460-0943c5660af4.jpg)

Hello, I'm currently stuck on this loading screen and cannot get past it. 

I had V4.2.0 so I followed the README and ended up here.

> 1. Ignore the Touchscreen firmware folder in the CF6.1-Final release zip file.
> 
> 2. INSTEAD, copy the DWIN_SET folder and contents from this release to the micro-SD card you use to flash the display 
> 
> 3. DO NOT copy ANY DGUS2 kernel upgrade files to the DWIN_SET folder before flashing it to your display.

**Comment by BubuMVX** [comment]
Hi !
Have you also updated the firmware of the motherboard with the corresponding version?

**Comment by wheetboi** [comment]
Hello,

I have not, the guide I was reading said to update that only after I handle the UI screen first.

**Comment by BubuMVX** [comment]
According to your screenshot, it looks like the update of the screen is OK.
After reading again the documentation, it seems to me you can keep the last Community Firmware for the motherboard, version 6.1.
Sorry in advance if I'm misleading you, I didn't test it and I didn't flash my printer since quite a long time.
Which version of the motherboard firmware are you using?

**Comment by wheetboi** [comment]
I believe the update is OK it's just not going past that full loading bar. 

This is my first time flashing the motherboard. I just tried to flash it with:

[CF6.1-Final-cr6-se-v4.5.3-mb-2021-06-04-16-53.zip](https://github.com/CR6Community/Marlin/releases/download/v2.0.8.1-cr6-community-release-6.1/CF6.1-Final-cr6-se-v4.5.3-mb-2021-06-04-16-53.zip)

However it's still just stuck at that loading bar, nothing else since then.

**Comment by BubuMVX** [comment]
And you have a motherboard revision 4.5.3 right?

**Comment by wheetboi** [comment]
I have a v1.1.0.3-ERA motherboard, which I believe according to the FAQs means I use the v4.5.3 file 
![image](https://user-images.githubusercontent.com/77525741/228956415-820c3c47-6c2a-4cf5-980c-f08676ba140b.png)

**Comment by BubuMVX** [comment]
Yes, perfect.
Are you flashing from the stock firmware to the community one, or are you trying to upgrade from another community firmware version?
If you're upgrading from the stock one, you way want to try the previous non-refactored version (only the touchscreen files inside the release ZIP):
https://github.com/CR6Community/Marlin/releases/v2.0.7.3-cr6-community-release-6
https://github.com/CR6Community/Marlin/releases/download/v2.0.7.3-cr6-community-release-6/CR6Comm-CF6-Final-cr6-se-v4.5.3-mb-2021-03-27-15-53.zip

**Comment by wheetboi** [comment]
Yes from stock firmware (I believe? I have done zero flashing before today so I assume I'm on everything stock 😂)

I'll give these a shot next. Do I need to do any reversion process or just flash em with the files above

**Comment by BubuMVX** [comment]
You can directly flash over the current firmware.

Sorry but I've posted an outdated version in my previous message (v6.0 instead of v6.1).
In the ZIP you mentioned before (`CF6.1-Final-cr6-se-v4.5.3-mb-2021-06-04-16-53.zip`), you can find the screen firmware in this path: `/Firmware/Touch screen firmware/CR-6-touchscreen-2021-06-04.zip`

Good luck !

**Comment by wheetboi** [comment]
![IMG_20230330_145255](https://user-images.githubusercontent.com/77525741/228962050-5d4fdf1c-f751-405d-ba7d-b15c739525f8.jpg)

Well it's definitely the non-refactored version. Still frozen on loading bar with or without trying to flash the mobo

**Comment by wheetboi** [comment]
In an attempt to just revert back and start fresh, I flashed back down to the stock firmware on the website and now everything is in Chinese and the touchscreen doesn't work 🙃 

https://www.creality.com/pages/download-cr-6-se?spm=..page_1934481.products_display_1.1&spm_prev=..index.header_1.1

**Comment by wheetboi** [comment]
I've tried every variation of firmwares for MOBO + Touchscreen from the site and nothing is making the touchscreen work.

Feel like it's just fried now, serves me right for trying to tinker. /shrug

**Comment by Thinkersbluff** [comment]
The motherboard and display firmwares are a matched set. There is no benefit to flashing random pairs. 

The interface will stick on the flash screen, if it does not hear from the motherboard. Eventually, you should see a message about the bootloader being confused, which is a reference to the motherboard bootloader. 

You can use M115 to find out which version of firmware is currently flashed to the motherboard. 
If the screen still sticks on the splash screen when M115 confirms that CF6.1 Final is flashed to the motherboard, then I would inspect the serial cable connecting the display to the motherboard, for signs of damage or loose pins. (The serial interface is on the middle two wires of the cable. )

**Comment by Thinkersbluff** [comment]
> I flashed back down to the stock firmware on the website and now everything is in Chinese and the touchscreen doesn't work

It is possible that the Creality firmware you flashed requires you to install DGUS2 v4.5 for the touchscreen to work. If you flashed backwards from 4.5 to 3.5 while installing one of the many firmwares you tried, that could stop the touchscreen from working. 

The file and instructions for flashing back to 4.5 are in the Refactored DWIN_SET zip file. 

I also have created this support documentation on GitBook: https://cr6community-support-team.gitbook.io/cr6comm-touchscreen-refactored-firmware-docs/introduction/welcome

**Comment by ritchiedc** [comment]
This is a bit confusing between here and discord (he didn't know about discord originally). He has flashed DGUS2 v4.5 but I don't know if he has tried going back to stock since then.

**Comment by Thinkersbluff** [comment]
I am still waiting to hear what M115 tells us about which firmware is on the mainboard.

**Comment by Thinkersbluff** [comment]
Unfortunately for others who may encounter this problem, the Author of this Issue solved the problem by trading the printer back to MicroCenter for something else...
I will close this issue.  

If someone else encounters this problem, please try the above recommendations before opening a new report.
